name: CI

on:
  push:
    branches: [main]
  release:
    types: [published]
  pull_request:
    types : [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-24.04
            compiler: gcc

          - platform: windows
            os: windows-2022
            compiler: msvc

    env:
      VCPKG_ROOT: vcpkg
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite

    steps:
      - uses: actions/checkout@v6

      - name: Set up MSVC (Windows)
        if: matrix.platform == 'windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install dependencies (Linux)
        if: matrix.platform == 'linux'
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y --no-install-recommends build-essential ninja-build lcov


      - name: Set up cache for VCPKG
        uses: actions/github-script@v9
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install VCPKG
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics

      - name: Configure HealthGPS (debug)
        run: |
          cmake --preset=${{ matrix.platform }}-debug -DWARNINGS_AS_ERRORS=ON -DGENERATE_COVERAGE=ON

      - uses: ZedThree/clang-tidy-review@v0.23.1
        if: matrix.platform == 'linux' && github.event_name == 'pull_request' && !(github.actor == 'dependabot[bot]' || github.actor == 'pre-commit-ci[bot]')
        id: review
        with:
          build_dir: out/build/linux-debug
          config_file: .clang-tidy
          lgtm_comment_body: ''

      # Upload clang-tidy fixes + fail CI if there are any comments
      - uses: ZedThree/clang-tidy-review/upload@v0.23.1
        if: matrix.platform == 'linux' && github.event_name == 'pull_request' && !(github.actor == 'dependabot[bot]' || github.actor == 'pre-commit-ci[bot]')
        id: upload-review

      - if: github.event_name == 'pull_request' && steps.review.outputs.total_comments > 0 && matrix.platform == 'linux' && !(github.actor == 'dependabot[bot]' || github.actor == 'pre-commit-ci[bot]')
        run: exit 1

      - uses: ammaraskar/gcc-problem-matcher@master
      - name: Build HealthGPS (debug)
        if: '!cancelled()'
        run: cmake --build --preset=${{ matrix.platform }}-debug-build --target=install

      - name: Execute HealthGPS (debug)
        if: '!cancelled()'
        run: out/install/${{ matrix.platform }}-debug/bin/HealthGPS.Console --help

      - name: Build HealthGPS (release)
        if: '!cancelled()'
        run: |
          # Build documentation so we can show Doxygen warnings
          cmake --preset=${{ matrix.platform }}-release -DWARNINGS_AS_ERRORS=ON -DBUILD_DOC=ON
          cmake --build --preset=${{ matrix.platform }}-release-build --target=install

      - name: Execute HealthGPS (release)
        if: '!cancelled()'
        run: out/install/${{ matrix.platform }}-release/bin/HealthGPS.Console --help

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: health-gps-${{ matrix.platform }}
          path: |
            ${{ github.workspace }}/out/install/${{ matrix.platform }}-*/*

      - name: Run tests
        run: ctest --preset=core-test-${{ matrix.platform }}

      - name: Generate coverage report
        if: matrix.platform == 'linux'
        working-directory: ${{github.workspace}}/out/build/${{ matrix.platform }}-debug
        run: geninfo . --include 'src/HealthGPS*' --exclude 'src/HealthGPS.Tests' --output-file main_coverage.info

      - name: Upload coverage reports to Codecov
        if: matrix.platform == 'linux'
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Zip output folder
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{github.workspace}}/out/install/${{ matrix.platform }}-release/bin/
        run: |
          mkdir ${{github.workspace}}/artifact
          7z a -tzip ${{github.workspace}}/artifact/health_gps_${{ matrix.platform }}.zip *.dll *.Console* schemas

      - name: Upload release artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: artifact/health_gps_${{ matrix.platform }}.zip
