name: Release
run-name: Publishing release ${{ github.ref_name }}

on:
  release:
    types: [published]

jobs:
  sha256:
    runs-on: ubuntu-latest

    steps:
      - name: Download release tarball
        run: |
          curl -O -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"

      - name: Generate sha256 checksum
        run: |
          sha256sum ${{ github.ref_name }}.tar.gz > sha256sum.txt

      - name: Upload sha256 checksum
        uses: softprops/action-gh-release@v3
        with:
          files: sha256sum.txt